"""Add imagen_url to vehicles

Revision ID: b10ddb3d69a1
Revises: da0a69a65e6e
Create Date: 2026-02-05 14:53:27.826567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b10ddb3d69a1'
down_revision: Union[str, None] = 'da0a69a65e6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('imagen_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles', 'imagen_url')
    # ### end Alembic commands ###
